name = "deerscape"
version = "0.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce8bb44e1d97597a78d2318aec9f1a8f4996055146cc7ce41de2bf36c0676cd6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
