name = "deerscape"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "273ec676a65995196667aec5b479644ee8a3a2a1bb062a8ead33571b65343aa0"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
