name = "deersmp"
author = "zxshima and friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6122095082b79e5918525ac99104f5b9ff53e47ea08adda63b6a33d69a9ab5ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
