name = "deerscape"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ab76942432714848b3eae9af91dc08f627daf8b420aa97f5ef42176b35f2292"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
