name = "deerscape"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1b92248d5a793de7edd0d4d14979682b02130a051af60a56e437d7c38aea767"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
