name = "deerscape"
version = "0.6.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb69fc71d5ff8916d07d4eb6eda83b5c603f668da393df7b5d16cb460474051"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
