name = "deerscape"
version = "0.7.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eac6242ba690a46450d6a2b0461fed4c337a836e2bf373fd7601e639a9245b15"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
