name = "deersmp"
author = "zxshima and friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "340473ce8b26163c5beb907f3e699e6bf05a122d73c5dc8c6ea611b9f5bc6973"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
