name = "deerscape"
version = "0.7.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb914995fc3f6ea5b3134d88cdcdfd827e68f955ec471479b2748ffd9e06cdd9"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
