name = "deerscape"
version = "0.7.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e30fb671fe49bf4faddb3863c8634bcec4a847009e97273314a2d3adda3c3fa8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
