name = "deerscape"
version = "0.7.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f474f888abd8ad2d41824a212a5524d9c4a8e643d649eca7cedc8639b4bd22e3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
