name = "deersmp"
author = "zxshima and friends"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "189e04e7566b4f8d6c805d8a95a293916ff57403fb8ee554ca279186a04e958b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
