
[misc]
	#If interacting with blocks like Flower Pots and Amendment Placeable Books should put the item they contain into your inventory, thus merging with existing stacks, instead of adding it to your hand, which is EXTREMELY ANNOYING
	"Less Annoying Item Reclaim" = true

[Vanilla]

	[Vanilla.metal_ores]
		#If mining ores that normally drop raw ores should grant XP
		"Experienced metal" = false

	[Vanilla.farmland]
		#Whether farmland can be untilled by sneak-right clicking them with a hoe
		"Untillable Farmland" = true

	[Vanilla.disc]
		#The disc that should be spawned when a jukebox is struck with lightning. Disables if string is "no"
		"Lightning Disc" = "minecraft:music_disc_ward"

	[Vanilla.xp]
		#If placing a block should have a chance to yield experience.
		"Experienced Building" = false
		#Specify n here, where the chance of a block dropping xp is 1/n. Integers only!
		"Building XP chance" = 64
		#If all blocks that are crops should drop experience.
		"Experienced Crops" = false
		#Minimum XP a crop block will drop when broken.
		"Minimum Crop XP" = 0
		#Maximum XP a crop block will drop when broken.
		"Maximum Crop XP" = 1

	[Vanilla.dispensers]
		#If dispensers should be able to dispense into cauldrons
		"Dispenser Cauldrons" = true

	[Vanilla.enchantments]
		#If enchantments other than protection should be buffed. Experimental!
		"Erm what the sigma" = true

[atmospheric]

	[atmospheric.Oranges]
		#If oranges can no longer be jumped on to be broken and to create a vapor cloud
		"Normal Oranges" = true

[farmersdelight]

	[farmersdelight."Knife Enchantments"]
		#If knives should no longer receive the silk touch and efficiency from the enchanting table
		"Unbloated Knife Enchantments" = true

["Mowzies Mobs"]

	["Mowzies Mobs".Rakes]
		#If hoes should also be able to rake sand. Disabled by default option for my modpack
		"Hoes Rake Sand" = false

[nethersdelight]

	[nethersdelight.fungus_colonies]
		#If fungus colonies should grow on normal rich soil instead of soul rich soil
		"Rich Fungus" = true

	[nethersdelight.bullet_peppers]
		#If bullet peppers should become unplaceable, thus killing letios plants forever
		"Kill letios plants" = true

	[nethersdelight.magma_cakes]
		#If frogs should become unable to consume magma cakes
		"Magma Cakes Good" = false

[supplementaries]

	[supplementaries.quivers]
		#If processing a quiver in a cutting board will eject all the arrows in that quiver
		"Realistic Quivers" = true

["Alexander Caverns"]

	["Alexander Caverns".Acid]
		#If acid should not corrode copper
		"Good Acid" = true

	["Alexander Caverns"."Cave Maps"]
		#If pathfinder quills should make a based sigma cave map instead of a cringe beta vanilla map
		"I'm sorry I said all that" = false

		["Alexander Caverns"."Cave Maps"."Biome Treats"]
			#If biome treats should work regardless of hunger
			"Okay Treats" = true

		["Alexander Caverns"."Cave Maps"."Sack of Sating"]
			#If sacks of sating no longer restore saturation
			"Mid sack of sating" = false

