#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			blue_mushroom = true
			red_mushroom = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_apple_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_apple_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_apple_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_apple_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_apple_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_apple_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = false
			pear_fruit = false

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.cluttered]
			willow = true
			flowering_willow = true
			poplar = true
			flowering_poplar = true
			crabapple = true
			flowering_crabapple = true
			sycamore = true
			fluorescent_maple = true
			flowering_fluorescent_maple = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.nomansland]
			silt = true

		[types.stone_type.architects_palette]
			abyssaline = true
			hadaline = true
			myonite = true
			esoterrack = true
			onyx = true
			wardstone = true
			moonshale = true
			nebulite = true

		[types.stone_type.spelunkery]
			nephrite = true

#Disables specific entries
[entries]

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			center_cut_log = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			edged_stripped_log = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			f_sign_stripped_log = true
			circle_glass_pane = true
			versailles_planks = true
			wise_stripped_log = true
			layered_stripped_log = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			planked_log = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			lumpy_stripped_log = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			chipped_stripped_log = true
			patient_stripped_log = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			overgrown_log = true
			meshed_trapdoor = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			k_sign_stripped_log = true
			double_herringbone_planks = true
			sign_stripped_log = true
			crated_planks = true
			knotted_stripped_log = true
			horizontal_lined_glass = true
			l_sign_stripped_log = true
			reinforced_log = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			reinforced_stripped_log = true
			slotted_trapdoor = true
			bundled_log = true
			shack_door = true
			polished_planks = true
			ornate_bared_glass_pane = true
			stern_stripped_log = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			carved_stripped_log = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			i_sign_stripped_log = true
			twisted_trapdoor = true
			d_sign_stripped_log = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			damaged_log = true
			golden_barred_trapdoor = true
			nailed_log = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			vertical_slab = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.nomansland]
			trimmed_planks = true
			bookshelf = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			board_wall = true
			railing = true
			boards = true
			board_slab = true

		[entries.leaves_type.chipped]
			magenta_flower_leaves = true
			golden_leaves = true
			apple_leaves = true
			frosted_leaves = true
			orange_leaves = true
			red_leaves = true
			cherry_leaves = true
			golden_cherry_leaves = true
			dead_leaves = true
			golden_apple_leaves = true
			white_flower_leaves = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.stone_type.chipped]
			tiled_column = true
			pillar = true
			checkered_tiles = true
			cracked_flat_tiles = true
			eroded = true
			weathered = true
			tiled_bordered = true
			simple_pillar = true
			scales = true
			smooth_column = true
			vertical_disordered_bricks = true
			fine_pillar = true
			sad = true
			brick_bordered = true
			glad = true
			smooth_inlayed = true
			unamused = true
			bordered = true
			cut_column = true
			edged_bricks = true
			cobbled = true
			smoothed_double_inlayed = true
			rounded_bricks = true
			overlapping_tiles = true
			pillar_top = true
			rough = true
			tiny_layered_bricks = true
			loded = true
			bricks = true
			massive_bricks = true
			layed_bricks = true
			spider_carving = true
			thick_inlayed = true
			tiny_brick_bordered = true
			pointed_dripstone = true
			sanded = true
			engraved = true
			offset_bricks = true
			small_bricks = true
			duh = true
			mini_tiles = true
			angry = true
			vertical_cut = true
			crying = true
			smooth_ringed = true
			runic_carved = true
			curly_pillar = true
			etched_bricks = true
			stacked_bricks = true
			spiraled = true
			inscribed = true
			polished = true
			cut_blank = true
			blank_carving = true
			prismal_remnants = true
			tiny_layered_slabs = true
			tiny_bricks = true
			flat_tiles = true
			inlayed = true
			trodden = true
			tiled = true
			creeper_carving = true
			cracked_bricks = true
			pillar_bricks = true
			cracked_disordered_bricks = true
			carved = true
			ornate_pillar = true

		[entries.stone_type.create]
			cut_wall = true
			small_bricks = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_brick_stairs = true
			cut_brick_slab = true
			polished_cut_slab = true
			polished_cut_wall = true
			cut_slab = true
			small_brick_wall = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			cut_stairs = true
			small_brick_stairs = true
			cut_bricks = true
			polished_cut_stairs = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

		[entries.mud_type.betterarcheology]
			cracked_brick_stairs = true
			cracked_bricks = true
			cracked_brick_slab = true
