name: Refresh and deploy

on:
    push:
        branches:
        - main
    
jobs:
    refresh:
        runs-on: ubuntu-latest
        permissions:
              contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6.0.2

            - name: Setup Go
              uses: actions/setup-go@v6.4.0

            - name: Install Packwiz
              run: go install github.com/packwiz/packwiz@latest

            - name: Run packwiz refresh
              run: packwiz refresh

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@v7
           
            - name: Upload artifacts
              uses: actions/upload-pages-artifact@v3
    deploy:
        needs: refresh
        permissions:
              pages: write
              id-token: write

        environment:
              name: github-pages
              url: ${{ steps.deployment.outputs.page_url }}
              
        runs-on: ubuntu-latest
        steps:
              - name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
